server:
  port: 8086
logging:
  level:
    org.apache.http.wire: info
    org.apache.http.headers: info

# 抢票线最大线程数量
max_pool_count : 1

12306:
 account: xxx
 pwd: xxx
  # 多余用，隔开。 目前不支持 多日抢票 （不是不会做 本仙就是懒得做。）
 # 可用值 商务座,特等座,一等座,二等座,高级软卧,软卧,硬卧,软座,硬座,无座
 #请不要输错车站名
ticket:
  date: xxx
  train_number: xxx
  seats: xxx
  departure : xxx
  arrival : xxx
  user_name: xxx


  # 本仙 没钱 所以没做 短信通知/语音电话通知抢票成功  使用 免费的 邮箱通知。
# 邮箱
spring:
  mail:
    auth: true
    default-encoding: utf-8
    host: xxx
    password: xxx
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    protocol: smtp
    username: xxx
to_email: xxx  #抢票成功接收人邮箱


